CREATE TABLE TARIFFS (
    TARIFF_ID    NUMBER(2)     NOT NULL,
    NAME         VARCHAR2(100) NOT NULL,
    MONTHLY_FEE  NUMBER(10,2)  NOT NULL,
    DATA_LIMIT   NUMBER(10,2)  DEFAULT 0 NOT NULL,
    MINUTE_LIMIT NUMBER(6)     DEFAULT 0 NOT NULL,
    SMS_LIMIT    NUMBER(6)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TARIFFS         PRIMARY KEY (TARIFF_ID),
    CONSTRAINT UQ_TARIFFS_NAME    UNIQUE (NAME),
    CONSTRAINT CHK_TARIFFS_FEE    CHECK (MONTHLY_FEE   >= 0),
    CONSTRAINT CHK_TARIFFS_DATA   CHECK (DATA_LIMIT    >= 0),
    CONSTRAINT CHK_TARIFFS_MINUTE CHECK (MINUTE_LIMIT  >= 0),
    CONSTRAINT CHK_TARIFFS_SMS    CHECK (SMS_LIMIT     >= 0)
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER(6)     NOT NULL,
    NAME        VARCHAR2(100) NOT NULL,
    CITY        VARCHAR2(100) NOT NULL,
    SIGNUP_DATE DATE          NOT NULL,
    TARIFF_ID   NUMBER(2)     NOT NULL,
    CONSTRAINT PK_CUSTOMERS       PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT FK_CUSTOMER_TARIFF FOREIGN KEY (TARIFF_ID) REFERENCES TARIFFS (TARIFF_ID)
);

CREATE TABLE MONTHLY_STATS (
    ID             NUMBER(6)     NOT NULL,
    CUSTOMER_ID    NUMBER(6)     NOT NULL,
    DATA_USAGE     NUMBER(10,2)  DEFAULT 0 NOT NULL,
    MINUTE_USAGE   NUMBER(6)     DEFAULT 0 NOT NULL,
    SMS_USAGE      NUMBER(6)     DEFAULT 0 NOT NULL,
    PAYMENT_STATUS VARCHAR2(10)  NOT NULL,
    CONSTRAINT PK_MONTHLY_STATS   PRIMARY KEY (ID),
    CONSTRAINT FK_STATS_CUSTOMER  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID),
    CONSTRAINT UQ_STATS_CUSTOMER  UNIQUE (CUSTOMER_ID),
    CONSTRAINT CHK_PAYMENT_STATUS CHECK (PAYMENT_STATUS IN ('PAID', 'LATE', 'UNPAID')),
    CONSTRAINT CHK_STATS_DATA     CHECK (DATA_USAGE    >= 0),
    CONSTRAINT CHK_STATS_MINUTE   CHECK (MINUTE_USAGE  >= 0),
    CONSTRAINT CHK_STATS_SMS      CHECK (SMS_USAGE     >= 0)
);

CREATE INDEX IDX_CUSTOMERS_TARIFF      ON CUSTOMERS     (TARIFF_ID);
CREATE INDEX IDX_CUSTOMERS_CITY        ON CUSTOMERS     (CITY);
CREATE INDEX IDX_CUSTOMERS_SIGNUP      ON CUSTOMERS     (SIGNUP_DATE);
CREATE INDEX IDX_CUSTOMERS_TARIFF_CITY ON CUSTOMERS     (TARIFF_ID, CITY);
CREATE INDEX IDX_STATS_PAYMENT         ON MONTHLY_STATS (PAYMENT_STATUS);
CREATE INDEX IDX_STATS_DATA_USAGE      ON MONTHLY_STATS (DATA_USAGE);
